FROM apache/superset:latest

USER root

# Install system dependencies for mysqlclient including pkg-config
RUN apt-get update && \
    apt-get install -y gcc default-libmysqlclient-dev build-essential pkg-config && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install both python MySQL drivers
RUN pip install pymysql mysqlclient

USER superset


